package com.hjc.cms.controller;

import com.hjc.cms.bean.Coupon;
import com.hjc.cms.bean.SellerCoupon;
import com.hjc.cms.bean.entity.PageResult;
import com.hjc.cms.dao.CouponRepository;
import com.hjc.cms.dao.SellerCouponRepository;
import com.hjc.cms.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


import java.util.Arrays;

/**
 * auto generated by gradle
 */

@RestController
@RequestMapping("seller-coupon")
public class SellerCouponController extends BaseController {
    @Autowired
    UserRepository userRepository;
    @Autowired
    SellerCouponRepository sellerCouponRepository;
    @Autowired
    CouponRepository couponRepository;

    @RequestMapping("obtain")
    public PageResult obtain(int page, int rows, SellerCoupon query) {
        //id 为当前用户id
        if(! isAdmin(currentUser())){
                query.setCoupon( new Coupon().setCreator(currentUser().getId()));
        }
        Page<SellerCoupon> list = sellerCouponRepository.findAll(Example.of(query, queryMatcher()), PageRequest.of(page-1, rows));
        return new PageResult(list.getTotalElements(),list.getContent());
    }

//    @RequestMapping("allSellers")
//    public PageContent allSellers(int manager) {
//        return page(userRepository.findByManager(manager));
//    }
//
//    @RequestMapping("save")
//    public void save(int[] sellerIds, int couponId, int count) {
//        Coupon coupon = couponRepository.findOne(couponId);
//        runSessionCommit(() ->
//                Arrays.stream(sellerIds).forEach(sellerId ->
//                        sellerCouponRepository.save(new SellerCoupon().setOccupied(0)
//                                .setCount(count).setUser(userRepository.getOne(sellerId)).setCoupon(coupon))));
//    }

}
