package com.hjc.cms.controller;

import com.hjc.cms.bean.Coupon;
import com.hjc.cms.bean.Park;
import com.hjc.cms.bean.SellerCoupon;
import com.hjc.cms.bean.User;
import com.hjc.cms.bean.entity.PageResult;
import com.hjc.cms.bean.entity.Result;
import com.hjc.cms.dao.CouponRepository;
import com.hjc.cms.dao.ParkRepository;
import com.hjc.cms.dao.SellerCouponRepository;
import com.hjc.cms.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * auto generated by gradle
 */

@RestController
@RequestMapping("seller-coupon")
public class SellerCouponController extends BaseController {
    @Autowired
    UserRepository userRepository;
    @Autowired
    SellerCouponRepository sellerCouponRepository;
    @Autowired
    CouponRepository couponRepository;
    @Autowired
    ParkRepository parkRepository;
    @RequestMapping("obtain")
    public PageResult obtain(int page, int rows, SellerCoupon query) {
        //id 为当前用户id
        if(! isAdmin(currentUser())){
                query.setCoupon( new Coupon().setCreator(currentUser().getId()));
        }
        Page<SellerCoupon> list = sellerCouponRepository.findAll(Example.of(query, queryMatcher()), PageRequest.of(page-1, rows));
        return new PageResult(list.getTotalElements(),list.getContent());
    }

    @RequestMapping("allSellers")
    public PageResult allSellers() {
        List<User> list ;
        if( isAdmin(currentUser())){
            list = userRepository.findByManagerNotNull();

        }else{
            //String[] strings = ;
          //  List<Park> park = parkRepository.findByParkIdIn(currentUserParkIds());
            list = userRepository.findByManager(currentUser().getId());
        }
        return  new PageResult( list.size(),list );
    }
    @RequestMapping("getUserMap")
    public Result getUserMap() {
        List<User> list ;
        HashMap<Integer, String>  map = new HashMap<>();
            list = userRepository.findByManagerIsNull();
          list.forEach(user->map.put(user.getId(),user.getName()));
        return  new Result( true, "ok").setInfo(map);
    }
//
//    @RequestMapping("save")
//    public void save(int[] sellerIds, int couponId, int count) {
//        Coupon coupon = couponRepository.findOne(couponId);
//        runSessionCommit(() ->
//                Arrays.stream(sellerIds).forEach(sellerId ->
//                        sellerCouponRepository.save(new SellerCoupon().setOccupied(0)
//                                .setCount(count).setUser(userRepository.getOne(sellerId)).setCoupon(coupon))));
//    }

}
