server:
  port: 8080
  servlet:
    context-path: /


spring:
#  mvc:
#    pathmatch:
#      use-suffix-pattern: false
#      use-registered-suffix-pattern: true
#    contentnegotiation:
#      favor-path-extension: false
  datasource:
    url: jdbc:mysql://t.hjcpay.com:3306/park?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 100
    maxActive: 1000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    #exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    #filter: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
# 定位模板的目录
  thymeleaf:
    prefix: classpath:/templates/
    # 给返回的页面添加后缀名
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5



mybatis:
  config-location: classpath:mybatis_config.xml
  mapper-locations: classpath:com/hjc/cms/dao/mapper/*Mapper.xml
  type-aliases-package: com.shangguan.mybatis.entity
