package com.hjc.cms.dao;

import com.hjc.cms.bean.Coupon;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;


import java.util.List;

/**
 * auto generated by gradle
 */

public interface CouponRepository extends JpaRepository<Coupon, Integer> {
    @Query("select o from Coupon o join Park p on o.park.id=p.parkId where p.parkId in :parkIds order by o.id desc")
    List<Coupon> findByParkIds(String[] parkIds);
}
