package com.hjc.cms.dao;

import com.hjc.cms.bean.ParkConfig;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * auto generated by gradle
 */
@Repository
public interface ParkConfigRepository extends JpaRepository<ParkConfig, String> {

}
