package com.hjc.cms.dao;

import com.hjc.cms.bean.SellerCoupon;
import org.springframework.data.jpa.repository.JpaRepository;


/**
 * auto generated by gradle
 */

public interface SellerCouponRepository extends JpaRepository<SellerCoupon, Integer> {
}
