package com.hjc.cms.dao;

import com.hjc.cms.bean.YlConfig;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
 * auto generated by gradle
 */
@Repository
public interface YlConfigRepository extends JpaRepository<YlConfig, Integer> {

}
